apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

namePrefix: prod-

commonLabels:
  environment: prod

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml
  - keda-scalers.yaml
  - prod-config.yaml

patches:
  - path: resource-patches.yaml
    target:
      kind: Deployment
