apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

namePrefix: staging-

commonLabels:
  environment: staging

resources:
  - ../../base

patches:
  - path: resource-patches.yaml
    target:
      kind: Deployment
  - path: staging-config.yaml
