apiVersion: apps/v1
kind: Deployment
metadata:
  name: any
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: staging
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              environment: staging
      containers:
        - name: "*"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
