apiVersion: apps/v1
kind: Deployment
metadata:
  name: any
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: staging
    spec:
      containers:
        - name: "*"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi
