apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ecommerce
type: Opaque
stringData:
  postgres-user: "ecommerce"
  postgres-password: "ecommerce-pass-2024"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: ecommerce
type: Opaque
stringData:
  username: "guest"
  password: "guest"
