apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: devops-ecommerce
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/ywlee/devops_dummpy.git
    targetRevision: HEAD
    path: manifests/overlays/staging
  destination:
    name: staging-cluster
    namespace: ecommerce
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
