apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-static
  namespace: ecommerce
  labels:
    app: nginx-static
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx-static
  endpoints:
    - port: http
      path: /stub_status
      interval: 15s
